### ISSUE TITLE
Update "Qui sommes nous ?" section

### ISSUE THREAD

**Issue by fe51** [pyronear/pyronear.github.io#30]
Tanks to Melissa, here's a suggestion for the "Qui sommes nous?" section, which is much easier to read, more accessible and more in line with our graphic identity. 

The use of "[cards](https://jekyllthemes.dev/a-simple-jekyll-template-card-based/)" from jekyll theme would certainly help to make this suggestion a reality!

happy to discuss it :)

![front](https://github.com/pyronear/pyronear.github.io/assets/55736935/b61cb933-756a-43b2-9bd5-33623264cd5d)

**Comment by ajubin** [comment]
Do you have the color code ? On the website, the theme primary is: #e89e5d

**Comment by fe51** [comment]
be free, be an artist 🎨  !

Otherwise, indeed, I just found the link to the mockup https://www.figma.com/proto/DssM8CCjdpx0E0NKtkIfav/Front?page-id=501%3A728&type=design&node-id=821-1719&viewport=1720%2C538%2C0.16&scaling=scale-down-width
