### ISSUE TITLE
Add Safety Innov Podcast

### ISSUE THREAD

**Issue by fe51** [pyronear/pyronear.github.io#32]
New podcast related to Pyronear, to add in our "ils parlent de nous" section.

It is available on different plateforme, here is the Spotify one 

https://open.spotify.com/episode/2NoEt2mCjhMDtlxeu594pG

**Comment by fe51** [comment]
As a logo, the image seen on spotify would be ok 
<img width="224" alt="image" src="https://github.com/pyronear/pyronear.github.io/assets/55736935/c77d9774-0c2c-47b5-99d5-0ccc391bdca9">

**Comment by ajubin** [comment]
ok
