### ISSUE TITLE
Fix logo not loading

### ISSUE THREAD

**Issue by fe51** [pyronear/pyronear.github.io#36]
Some logos from our sponsor or partner does not load, it has to be fixed

- CENIA : seems that's  the current link is pointing to not existing page
<img width="1252" alt="image" src="https://github.com/pyronear/pyronear.github.io/assets/55736935/4950976d-01da-4c29-be7b-9a91f66287af">

- M33 fondation, similar
<img width="1252" alt="image" src="https://github.com/pyronear/pyronear.github.io/assets/55736935/71f4e3f7-92c4-4c69-b2aa-6b9b8ab06c62">

It would be very helpful to fix this. Happy to discuss it !

**Comment by fe51** [comment]
@MateoLostanlen where did you find the M33 foundation logo? (what does it look like? )

**Comment by ajubin** [comment]
Je prend l'issue

**Comment by abdul-muyeed** [comment]
![image](https://github.com/pyronear/pyronear.github.io/assets/102542790/b9140cb3-b91f-4dd8-ad83-1d5963431b34)

is this the logo you are looking for?

**Comment by fe51** [comment]
Aller nice, Merci Jubin ! 😄 

Yes, exactly @abdul-muyeed  !

**Comment by abdul-muyeed** [comment]
Is there any specific repo Branch where I should make the pull request? Or should I make a new branch?

**Comment by ajubin** [comment]
@abdul-muyeed I did the PR, just seeing your messages
