### ISSUE TITLE
Add TedxTours video quoting Pyronear to "ils parlent de nous" section.

### ISSUE THREAD

**Issue by fe51** [pyronear/pyronear.github.io#39]
New vidéo quoting Pyronear (Thanks Lou :)) to add in our "ils parlent de nous" section.

The link to the video : https://www.youtube.com/watch?v=ZaBdnqnLVBg&ab_channel=TEDxTalks

Logo to retrieve here : https://www.tedxtours.com/

**Comment by ajubin** [comment]
ok
