### ISSUE TITLE
Support for other languages (English notably)

### ISSUE THREAD

**Issue by blenzi** [pyronear/pyronear.github.io#4]
Very nice first version @frgfm ! I believe it was foreseen to have support for other languages, just leaving a reminder.

**Comment by frgfm** [comment]
Thanks for opening this!
I actually have already added the content in English over there: https://github.com/pyronear/pyronear.github.io/blob/master/_config.yml#L66

But I'm still unsure about how we should add this on the website. Any idea @aaadryyy :pray: ? (my web dev skills are a bit rusty)
