### ISSUE TITLE
Add Europe1 describing Pyronear in "ils parlent de nous" section.

### ISSUE THREAD

**Issue by fe51** [pyronear/pyronear.github.io#40]
New vidéo about Pyronear , in the news at Europe1,  to add in "ils parlent de nous" section.

 [The link to the video](https://www.europe1.fr/emissions/initiative-a-impact/la-lutte-contre-les-feux-de-foret-passe-aussi-par-les-algorithmes-4204947)

Logo to retrieve here : https://www.europe1.fr/

**Comment by ajubin** [comment]
je susis dessus
