### ISSUE TITLE
Article in TechniqueDeL'ingénieur to add in "ils parlent de nous" section

### ISSUE THREAD

**Issue by fe51** [pyronear/pyronear.github.io#48]
Article dedicated to Pyronear in Technique de l'ingénieur to add in our "ils parlent de nous" section.

The link to the article :

https://www.techniques-ingenieur.fr/actualite/articles/comment-lia-permet-de-detecter-plus-rapidement-les-incendies-129238/?utm_source=linkedin&utm_medium=social&utm_campaign=72-WM-FY1LKDN&utm_content=ap_qgnbyezfjr

link to the logo : https://cdn.techniques-ingenieur.fr/lucy/ti/cdn.prod.v2.1.0/images/logo-eti.png

**Comment by mondiriariana** [comment]
Hi! Je m'en charge

**Comment by mondiriariana** [comment]
J'ai cree une pull request please review

> Hi! Je m'en charge
